// Code generated by protoc-gen-go. DO NOT EDIT.
// source: offer.proto

package offer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Mode int32

const (
	Mode_ByUser Mode = 0
	Mode_All    Mode = 1
)

var Mode_name = map[int32]string{
	0: "ByUser",
	1: "All",
}
var Mode_value = map[string]int32{
	"ByUser": 0,
	"All":    1,
}

func (x Mode) String() string {
	return proto.EnumName(Mode_name, int32(x))
}
func (Mode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{0}
}

type Status int32

const (
	Status_OfferNew       Status = 0
	Status_OfferActive    Status = 1
	Status_OfferPause     Status = 2
	Status_OfferInArchive Status = 3
)

var Status_name = map[int32]string{
	0: "OfferNew",
	1: "OfferActive",
	2: "OfferPause",
	3: "OfferInArchive",
}
var Status_value = map[string]int32{
	"OfferNew":       0,
	"OfferActive":    1,
	"OfferPause":     2,
	"OfferInArchive": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}
func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{1}
}

type OrderType int32

const (
	OrderType_ASC  OrderType = 0
	OrderType_DESC OrderType = 1
)

var OrderType_name = map[int32]string{
	0: "ASC",
	1: "DESC",
}
var OrderType_value = map[string]int32{
	"ASC":  0,
	"DESC": 1,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}
func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{2}
}

type Offer struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Uuid                 string               `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CategoryId           int32                `protobuf:"varint,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	DecisionId           int32                `protobuf:"varint,6,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	AdUserId             int32                `protobuf:"varint,7,opt,name=ad_user_id,json=adUserId,proto3" json:"ad_user_id,omitempty"`
	AdHash               string               `protobuf:"bytes,8,opt,name=ad_hash,json=adHash,proto3" json:"ad_hash,omitempty"`
	AdUrl                string               `protobuf:"bytes,9,opt,name=ad_url,json=adUrl,proto3" json:"ad_url,omitempty"`
	AdToken              string               `protobuf:"bytes,10,opt,name=ad_token,json=adToken,proto3" json:"ad_token,omitempty"`
	AdCoefficient        float64              `protobuf:"fixed64,11,opt,name=ad_coefficient,json=adCoefficient,proto3" json:"ad_coefficient,omitempty"`
	Name                 string               `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`
	NameComposite        string               `protobuf:"bytes,13,opt,name=name_composite,json=nameComposite,proto3" json:"name_composite,omitempty"`
	Status               int32                `protobuf:"varint,14,opt,name=status,proto3" json:"status,omitempty"`
	Transit              bool                 `protobuf:"varint,15,opt,name=transit,proto3" json:"transit,omitempty"`
	ApiIframe            bool                 `protobuf:"varint,16,opt,name=api_iframe,json=apiIframe,proto3" json:"api_iframe,omitempty"`
	Currency             string               `protobuf:"bytes,17,opt,name=currency,proto3" json:"currency,omitempty"`
	Link                 string               `protobuf:"bytes,18,opt,name=link,proto3" json:"link,omitempty"`
	Rule                 string               `protobuf:"bytes,19,opt,name=rule,proto3" json:"rule,omitempty"`
	Description          string               `protobuf:"bytes,20,opt,name=description,proto3" json:"description,omitempty"`
	Advice               string               `protobuf:"bytes,21,opt,name=advice,proto3" json:"advice,omitempty"`
	Source               string               `protobuf:"bytes,22,opt,name=source,proto3" json:"source,omitempty"`
	Price                float64              `protobuf:"fixed64,23,opt,name=price,proto3" json:"price,omitempty"`
	PriceCurrency        string               `protobuf:"bytes,24,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	CapEnable            bool                 `protobuf:"varint,25,opt,name=cap_enable,json=capEnable,proto3" json:"cap_enable,omitempty"`
	CapDaily             int32                `protobuf:"varint,26,opt,name=cap_daily,json=capDaily,proto3" json:"cap_daily,omitempty"`
	CapType              int32                `protobuf:"varint,27,opt,name=cap_type,json=capType,proto3" json:"cap_type,omitempty"`
	Visibility           int32                `protobuf:"varint,28,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Rank                 float64              `protobuf:"fixed64,29,opt,name=rank,proto3" json:"rank,omitempty"`
	Approved             float64              `protobuf:"fixed64,30,opt,name=approved,proto3" json:"approved,omitempty"`
	Daily                bool                 `protobuf:"varint,31,opt,name=daily,proto3" json:"daily,omitempty"`
	ImgAvatar            string               `protobuf:"bytes,32,opt,name=img_avatar,json=imgAvatar,proto3" json:"img_avatar,omitempty"`
	ImgProduct           string               `protobuf:"bytes,33,opt,name=img_product,json=imgProduct,proto3" json:"img_product,omitempty"`
	MaterialLink         string               `protobuf:"bytes,34,opt,name=material_link,json=materialLink,proto3" json:"material_link,omitempty"`
	Availability         int32                `protobuf:"varint,35,opt,name=availability,proto3" json:"availability,omitempty"`
	Pills                int32                `protobuf:"varint,36,opt,name=pills,proto3" json:"pills,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Offer) Reset()         { *m = Offer{} }
func (m *Offer) String() string { return proto.CompactTextString(m) }
func (*Offer) ProtoMessage()    {}
func (*Offer) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{0}
}
func (m *Offer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Offer.Unmarshal(m, b)
}
func (m *Offer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Offer.Marshal(b, m, deterministic)
}
func (dst *Offer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Offer.Merge(dst, src)
}
func (m *Offer) XXX_Size() int {
	return xxx_messageInfo_Offer.Size(m)
}
func (m *Offer) XXX_DiscardUnknown() {
	xxx_messageInfo_Offer.DiscardUnknown(m)
}

var xxx_messageInfo_Offer proto.InternalMessageInfo

func (m *Offer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Offer) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Offer) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Offer) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Offer) GetCategoryId() int32 {
	if m != nil {
		return m.CategoryId
	}
	return 0
}

func (m *Offer) GetDecisionId() int32 {
	if m != nil {
		return m.DecisionId
	}
	return 0
}

func (m *Offer) GetAdUserId() int32 {
	if m != nil {
		return m.AdUserId
	}
	return 0
}

func (m *Offer) GetAdHash() string {
	if m != nil {
		return m.AdHash
	}
	return ""
}

func (m *Offer) GetAdUrl() string {
	if m != nil {
		return m.AdUrl
	}
	return ""
}

func (m *Offer) GetAdToken() string {
	if m != nil {
		return m.AdToken
	}
	return ""
}

func (m *Offer) GetAdCoefficient() float64 {
	if m != nil {
		return m.AdCoefficient
	}
	return 0
}

func (m *Offer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Offer) GetNameComposite() string {
	if m != nil {
		return m.NameComposite
	}
	return ""
}

func (m *Offer) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Offer) GetTransit() bool {
	if m != nil {
		return m.Transit
	}
	return false
}

func (m *Offer) GetApiIframe() bool {
	if m != nil {
		return m.ApiIframe
	}
	return false
}

func (m *Offer) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Offer) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Offer) GetRule() string {
	if m != nil {
		return m.Rule
	}
	return ""
}

func (m *Offer) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Offer) GetAdvice() string {
	if m != nil {
		return m.Advice
	}
	return ""
}

func (m *Offer) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Offer) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Offer) GetPriceCurrency() string {
	if m != nil {
		return m.PriceCurrency
	}
	return ""
}

func (m *Offer) GetCapEnable() bool {
	if m != nil {
		return m.CapEnable
	}
	return false
}

func (m *Offer) GetCapDaily() int32 {
	if m != nil {
		return m.CapDaily
	}
	return 0
}

func (m *Offer) GetCapType() int32 {
	if m != nil {
		return m.CapType
	}
	return 0
}

func (m *Offer) GetVisibility() int32 {
	if m != nil {
		return m.Visibility
	}
	return 0
}

func (m *Offer) GetRank() float64 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *Offer) GetApproved() float64 {
	if m != nil {
		return m.Approved
	}
	return 0
}

func (m *Offer) GetDaily() bool {
	if m != nil {
		return m.Daily
	}
	return false
}

func (m *Offer) GetImgAvatar() string {
	if m != nil {
		return m.ImgAvatar
	}
	return ""
}

func (m *Offer) GetImgProduct() string {
	if m != nil {
		return m.ImgProduct
	}
	return ""
}

func (m *Offer) GetMaterialLink() string {
	if m != nil {
		return m.MaterialLink
	}
	return ""
}

func (m *Offer) GetAvailability() int32 {
	if m != nil {
		return m.Availability
	}
	return 0
}

func (m *Offer) GetPills() int32 {
	if m != nil {
		return m.Pills
	}
	return 0
}

type GetOfferRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOfferRequest) Reset()         { *m = GetOfferRequest{} }
func (m *GetOfferRequest) String() string { return proto.CompactTextString(m) }
func (*GetOfferRequest) ProtoMessage()    {}
func (*GetOfferRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{1}
}
func (m *GetOfferRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOfferRequest.Unmarshal(m, b)
}
func (m *GetOfferRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOfferRequest.Marshal(b, m, deterministic)
}
func (dst *GetOfferRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOfferRequest.Merge(dst, src)
}
func (m *GetOfferRequest) XXX_Size() int {
	return xxx_messageInfo_GetOfferRequest.Size(m)
}
func (m *GetOfferRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOfferRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOfferRequest proto.InternalMessageInfo

func (m *GetOfferRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Visibility struct {
	Mode                 Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=offer.Mode" json:"mode,omitempty"`
	AffiliateId          int32    `protobuf:"varint,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Visibility) Reset()         { *m = Visibility{} }
func (m *Visibility) String() string { return proto.CompactTextString(m) }
func (*Visibility) ProtoMessage()    {}
func (*Visibility) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{2}
}
func (m *Visibility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Visibility.Unmarshal(m, b)
}
func (m *Visibility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Visibility.Marshal(b, m, deterministic)
}
func (dst *Visibility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Visibility.Merge(dst, src)
}
func (m *Visibility) XXX_Size() int {
	return xxx_messageInfo_Visibility.Size(m)
}
func (m *Visibility) XXX_DiscardUnknown() {
	xxx_messageInfo_Visibility.DiscardUnknown(m)
}

var xxx_messageInfo_Visibility proto.InternalMessageInfo

func (m *Visibility) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_ByUser
}

func (m *Visibility) GetAffiliateId() int32 {
	if m != nil {
		return m.AffiliateId
	}
	return 0
}

type Availability struct {
	Mode                 Mode     `protobuf:"varint,1,opt,name=mode,proto3,enum=offer.Mode" json:"mode,omitempty"`
	AffiliateId          int32    `protobuf:"varint,2,opt,name=affiliate_id,json=affiliateId,proto3" json:"affiliate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Availability) Reset()         { *m = Availability{} }
func (m *Availability) String() string { return proto.CompactTextString(m) }
func (*Availability) ProtoMessage()    {}
func (*Availability) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{3}
}
func (m *Availability) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Availability.Unmarshal(m, b)
}
func (m *Availability) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Availability.Marshal(b, m, deterministic)
}
func (dst *Availability) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Availability.Merge(dst, src)
}
func (m *Availability) XXX_Size() int {
	return xxx_messageInfo_Availability.Size(m)
}
func (m *Availability) XXX_DiscardUnknown() {
	xxx_messageInfo_Availability.DiscardUnknown(m)
}

var xxx_messageInfo_Availability proto.InternalMessageInfo

func (m *Availability) GetMode() Mode {
	if m != nil {
		return m.Mode
	}
	return Mode_ByUser
}

func (m *Availability) GetAffiliateId() int32 {
	if m != nil {
		return m.AffiliateId
	}
	return 0
}

type ListOffersRequest struct {
	Limit                int32         `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               int32         `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Ids                  []int32       `protobuf:"varint,3,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Visibility           *Visibility   `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	Availability         *Availability `protobuf:"bytes,5,opt,name=availability,proto3" json:"availability,omitempty"`
	Statuses             []Status      `protobuf:"varint,6,rep,packed,name=statuses,proto3,enum=offer.Status" json:"statuses,omitempty"`
	OrderBy              string        `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderType            OrderType     `protobuf:"varint,8,opt,name=order_type,json=orderType,proto3,enum=offer.OrderType" json:"order_type,omitempty"`
	GeoCode              string        `protobuf:"bytes,9,opt,name=geo_code,json=geoCode,proto3" json:"geo_code,omitempty"`
	Search               string        `protobuf:"bytes,10,opt,name=search,proto3" json:"search,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListOffersRequest) Reset()         { *m = ListOffersRequest{} }
func (m *ListOffersRequest) String() string { return proto.CompactTextString(m) }
func (*ListOffersRequest) ProtoMessage()    {}
func (*ListOffersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{4}
}
func (m *ListOffersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOffersRequest.Unmarshal(m, b)
}
func (m *ListOffersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOffersRequest.Marshal(b, m, deterministic)
}
func (dst *ListOffersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOffersRequest.Merge(dst, src)
}
func (m *ListOffersRequest) XXX_Size() int {
	return xxx_messageInfo_ListOffersRequest.Size(m)
}
func (m *ListOffersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOffersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOffersRequest proto.InternalMessageInfo

func (m *ListOffersRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ListOffersRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListOffersRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListOffersRequest) GetVisibility() *Visibility {
	if m != nil {
		return m.Visibility
	}
	return nil
}

func (m *ListOffersRequest) GetAvailability() *Availability {
	if m != nil {
		return m.Availability
	}
	return nil
}

func (m *ListOffersRequest) GetStatuses() []Status {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func (m *ListOffersRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *ListOffersRequest) GetOrderType() OrderType {
	if m != nil {
		return m.OrderType
	}
	return OrderType_ASC
}

func (m *ListOffersRequest) GetGeoCode() string {
	if m != nil {
		return m.GeoCode
	}
	return ""
}

func (m *ListOffersRequest) GetSearch() string {
	if m != nil {
		return m.Search
	}
	return ""
}

type ListOffersResponse struct {
	Offers               []*Offer `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	Total                int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOffersResponse) Reset()         { *m = ListOffersResponse{} }
func (m *ListOffersResponse) String() string { return proto.CompactTextString(m) }
func (*ListOffersResponse) ProtoMessage()    {}
func (*ListOffersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{5}
}
func (m *ListOffersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOffersResponse.Unmarshal(m, b)
}
func (m *ListOffersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOffersResponse.Marshal(b, m, deterministic)
}
func (dst *ListOffersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOffersResponse.Merge(dst, src)
}
func (m *ListOffersResponse) XXX_Size() int {
	return xxx_messageInfo_ListOffersResponse.Size(m)
}
func (m *ListOffersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOffersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOffersResponse proto.InternalMessageInfo

func (m *ListOffersResponse) GetOffers() []*Offer {
	if m != nil {
		return m.Offers
	}
	return nil
}

func (m *ListOffersResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type Category struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{6}
}
func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (dst *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(dst, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListCategoriesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCategoriesRequest) Reset()         { *m = ListCategoriesRequest{} }
func (m *ListCategoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesRequest) ProtoMessage()    {}
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{7}
}
func (m *ListCategoriesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesRequest.Unmarshal(m, b)
}
func (m *ListCategoriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesRequest.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesRequest.Merge(dst, src)
}
func (m *ListCategoriesRequest) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesRequest.Size(m)
}
func (m *ListCategoriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesRequest proto.InternalMessageInfo

type ListCategoriesResponse struct {
	Categories           []*Category `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListCategoriesResponse) Reset()         { *m = ListCategoriesResponse{} }
func (m *ListCategoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListCategoriesResponse) ProtoMessage()    {}
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{8}
}
func (m *ListCategoriesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCategoriesResponse.Unmarshal(m, b)
}
func (m *ListCategoriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCategoriesResponse.Marshal(b, m, deterministic)
}
func (dst *ListCategoriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCategoriesResponse.Merge(dst, src)
}
func (m *ListCategoriesResponse) XXX_Size() int {
	return xxx_messageInfo_ListCategoriesResponse.Size(m)
}
func (m *ListCategoriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCategoriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCategoriesResponse proto.InternalMessageInfo

func (m *ListCategoriesResponse) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Goal struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	OfferId              int32                `protobuf:"varint,4,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Type                 int32                `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"`
	Coefficient          float64              `protobuf:"fixed64,6,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	PayIn                float64              `protobuf:"fixed64,7,opt,name=pay_in,json=payIn,proto3" json:"pay_in,omitempty"`
	PayOut               float64              `protobuf:"fixed64,8,opt,name=pay_out,json=payOut,proto3" json:"pay_out,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Goal) Reset()         { *m = Goal{} }
func (m *Goal) String() string { return proto.CompactTextString(m) }
func (*Goal) ProtoMessage()    {}
func (*Goal) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{9}
}
func (m *Goal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goal.Unmarshal(m, b)
}
func (m *Goal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goal.Marshal(b, m, deterministic)
}
func (dst *Goal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goal.Merge(dst, src)
}
func (m *Goal) XXX_Size() int {
	return xxx_messageInfo_Goal.Size(m)
}
func (m *Goal) XXX_DiscardUnknown() {
	xxx_messageInfo_Goal.DiscardUnknown(m)
}

var xxx_messageInfo_Goal proto.InternalMessageInfo

func (m *Goal) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Goal) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Goal) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func (m *Goal) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *Goal) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Goal) GetCoefficient() float64 {
	if m != nil {
		return m.Coefficient
	}
	return 0
}

func (m *Goal) GetPayIn() float64 {
	if m != nil {
		return m.PayIn
	}
	return 0
}

func (m *Goal) GetPayOut() float64 {
	if m != nil {
		return m.PayOut
	}
	return 0
}

type GetGoalRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OfferId              int32    `protobuf:"varint,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoalRequest) Reset()         { *m = GetGoalRequest{} }
func (m *GetGoalRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoalRequest) ProtoMessage()    {}
func (*GetGoalRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{10}
}
func (m *GetGoalRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoalRequest.Unmarshal(m, b)
}
func (m *GetGoalRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoalRequest.Marshal(b, m, deterministic)
}
func (dst *GetGoalRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoalRequest.Merge(dst, src)
}
func (m *GetGoalRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoalRequest.Size(m)
}
func (m *GetGoalRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoalRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoalRequest proto.InternalMessageInfo

func (m *GetGoalRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetGoalRequest) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

type ListGoalsRequest struct {
	Ids                  []int32  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	OfferIds             []int32  `protobuf:"varint,2,rep,packed,name=offer_ids,json=offerIds,proto3" json:"offer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGoalsRequest) Reset()         { *m = ListGoalsRequest{} }
func (m *ListGoalsRequest) String() string { return proto.CompactTextString(m) }
func (*ListGoalsRequest) ProtoMessage()    {}
func (*ListGoalsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{11}
}
func (m *ListGoalsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGoalsRequest.Unmarshal(m, b)
}
func (m *ListGoalsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGoalsRequest.Marshal(b, m, deterministic)
}
func (dst *ListGoalsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGoalsRequest.Merge(dst, src)
}
func (m *ListGoalsRequest) XXX_Size() int {
	return xxx_messageInfo_ListGoalsRequest.Size(m)
}
func (m *ListGoalsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGoalsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListGoalsRequest proto.InternalMessageInfo

func (m *ListGoalsRequest) GetIds() []int32 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListGoalsRequest) GetOfferIds() []int32 {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

type ListGoalsResponse struct {
	Goals                []*Goal  `protobuf:"bytes,1,rep,name=goals,proto3" json:"goals,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGoalsResponse) Reset()         { *m = ListGoalsResponse{} }
func (m *ListGoalsResponse) String() string { return proto.CompactTextString(m) }
func (*ListGoalsResponse) ProtoMessage()    {}
func (*ListGoalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{12}
}
func (m *ListGoalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGoalsResponse.Unmarshal(m, b)
}
func (m *ListGoalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGoalsResponse.Marshal(b, m, deterministic)
}
func (dst *ListGoalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGoalsResponse.Merge(dst, src)
}
func (m *ListGoalsResponse) XXX_Size() int {
	return xxx_messageInfo_ListGoalsResponse.Size(m)
}
func (m *ListGoalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGoalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListGoalsResponse proto.InternalMessageInfo

func (m *ListGoalsResponse) GetGoals() []*Goal {
	if m != nil {
		return m.Goals
	}
	return nil
}

type OfferGeoCode struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OfferId              int32    `protobuf:"varint,2,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferGeoCode) Reset()         { *m = OfferGeoCode{} }
func (m *OfferGeoCode) String() string { return proto.CompactTextString(m) }
func (*OfferGeoCode) ProtoMessage()    {}
func (*OfferGeoCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{13}
}
func (m *OfferGeoCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferGeoCode.Unmarshal(m, b)
}
func (m *OfferGeoCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferGeoCode.Marshal(b, m, deterministic)
}
func (dst *OfferGeoCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferGeoCode.Merge(dst, src)
}
func (m *OfferGeoCode) XXX_Size() int {
	return xxx_messageInfo_OfferGeoCode.Size(m)
}
func (m *OfferGeoCode) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferGeoCode.DiscardUnknown(m)
}

var xxx_messageInfo_OfferGeoCode proto.InternalMessageInfo

func (m *OfferGeoCode) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OfferGeoCode) GetOfferId() int32 {
	if m != nil {
		return m.OfferId
	}
	return 0
}

func (m *OfferGeoCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type ListOfferGeoCodesRequest struct {
	OfferIds             []int32  `protobuf:"varint,1,rep,packed,name=offer_ids,json=offerIds,proto3" json:"offer_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfferGeoCodesRequest) Reset()         { *m = ListOfferGeoCodesRequest{} }
func (m *ListOfferGeoCodesRequest) String() string { return proto.CompactTextString(m) }
func (*ListOfferGeoCodesRequest) ProtoMessage()    {}
func (*ListOfferGeoCodesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{14}
}
func (m *ListOfferGeoCodesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfferGeoCodesRequest.Unmarshal(m, b)
}
func (m *ListOfferGeoCodesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfferGeoCodesRequest.Marshal(b, m, deterministic)
}
func (dst *ListOfferGeoCodesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfferGeoCodesRequest.Merge(dst, src)
}
func (m *ListOfferGeoCodesRequest) XXX_Size() int {
	return xxx_messageInfo_ListOfferGeoCodesRequest.Size(m)
}
func (m *ListOfferGeoCodesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfferGeoCodesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfferGeoCodesRequest proto.InternalMessageInfo

func (m *ListOfferGeoCodesRequest) GetOfferIds() []int32 {
	if m != nil {
		return m.OfferIds
	}
	return nil
}

type ListOfferGeoCodesResponse struct {
	OfferGeoCodes        []*OfferGeoCode `protobuf:"bytes,1,rep,name=offer_geo_codes,json=offerGeoCodes,proto3" json:"offer_geo_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListOfferGeoCodesResponse) Reset()         { *m = ListOfferGeoCodesResponse{} }
func (m *ListOfferGeoCodesResponse) String() string { return proto.CompactTextString(m) }
func (*ListOfferGeoCodesResponse) ProtoMessage()    {}
func (*ListOfferGeoCodesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{15}
}
func (m *ListOfferGeoCodesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfferGeoCodesResponse.Unmarshal(m, b)
}
func (m *ListOfferGeoCodesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfferGeoCodesResponse.Marshal(b, m, deterministic)
}
func (dst *ListOfferGeoCodesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfferGeoCodesResponse.Merge(dst, src)
}
func (m *ListOfferGeoCodesResponse) XXX_Size() int {
	return xxx_messageInfo_ListOfferGeoCodesResponse.Size(m)
}
func (m *ListOfferGeoCodesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfferGeoCodesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfferGeoCodesResponse proto.InternalMessageInfo

func (m *ListOfferGeoCodesResponse) GetOfferGeoCodes() []*OfferGeoCode {
	if m != nil {
		return m.OfferGeoCodes
	}
	return nil
}

type TotalInfo struct {
	CountOffer           int32    `protobuf:"varint,1,opt,name=count_offer,json=countOffer,proto3" json:"count_offer,omitempty"`
	CountCategory        int32    `protobuf:"varint,2,opt,name=count_category,json=countCategory,proto3" json:"count_category,omitempty"`
	CountGeo             int32    `protobuf:"varint,3,opt,name=count_geo,json=countGeo,proto3" json:"count_geo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalInfo) Reset()         { *m = TotalInfo{} }
func (m *TotalInfo) String() string { return proto.CompactTextString(m) }
func (*TotalInfo) ProtoMessage()    {}
func (*TotalInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_offer_ea72e05c5e52454e, []int{16}
}
func (m *TotalInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalInfo.Unmarshal(m, b)
}
func (m *TotalInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalInfo.Marshal(b, m, deterministic)
}
func (dst *TotalInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalInfo.Merge(dst, src)
}
func (m *TotalInfo) XXX_Size() int {
	return xxx_messageInfo_TotalInfo.Size(m)
}
func (m *TotalInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TotalInfo proto.InternalMessageInfo

func (m *TotalInfo) GetCountOffer() int32 {
	if m != nil {
		return m.CountOffer
	}
	return 0
}

func (m *TotalInfo) GetCountCategory() int32 {
	if m != nil {
		return m.CountCategory
	}
	return 0
}

func (m *TotalInfo) GetCountGeo() int32 {
	if m != nil {
		return m.CountGeo
	}
	return 0
}

func init() {
	proto.RegisterType((*Offer)(nil), "offer.Offer")
	proto.RegisterType((*GetOfferRequest)(nil), "offer.GetOfferRequest")
	proto.RegisterType((*Visibility)(nil), "offer.Visibility")
	proto.RegisterType((*Availability)(nil), "offer.Availability")
	proto.RegisterType((*ListOffersRequest)(nil), "offer.ListOffersRequest")
	proto.RegisterType((*ListOffersResponse)(nil), "offer.ListOffersResponse")
	proto.RegisterType((*Category)(nil), "offer.Category")
	proto.RegisterType((*ListCategoriesRequest)(nil), "offer.ListCategoriesRequest")
	proto.RegisterType((*ListCategoriesResponse)(nil), "offer.ListCategoriesResponse")
	proto.RegisterType((*Goal)(nil), "offer.Goal")
	proto.RegisterType((*GetGoalRequest)(nil), "offer.GetGoalRequest")
	proto.RegisterType((*ListGoalsRequest)(nil), "offer.ListGoalsRequest")
	proto.RegisterType((*ListGoalsResponse)(nil), "offer.ListGoalsResponse")
	proto.RegisterType((*OfferGeoCode)(nil), "offer.OfferGeoCode")
	proto.RegisterType((*ListOfferGeoCodesRequest)(nil), "offer.ListOfferGeoCodesRequest")
	proto.RegisterType((*ListOfferGeoCodesResponse)(nil), "offer.ListOfferGeoCodesResponse")
	proto.RegisterType((*TotalInfo)(nil), "offer.TotalInfo")
	proto.RegisterEnum("offer.Mode", Mode_name, Mode_value)
	proto.RegisterEnum("offer.Status", Status_name, Status_value)
	proto.RegisterEnum("offer.OrderType", OrderType_name, OrderType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OfferServiceClient is the client API for OfferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OfferServiceClient interface {
	GetOffer(ctx context.Context, in *GetOfferRequest, opts ...grpc.CallOption) (*Offer, error)
	ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error)
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*Goal, error)
	ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error)
	ListOfferGeoCodes(ctx context.Context, in *ListOfferGeoCodesRequest, opts ...grpc.CallOption) (*ListOfferGeoCodesResponse, error)
	GetTotalInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TotalInfo, error)
}

type offerServiceClient struct {
	cc *grpc.ClientConn
}

func NewOfferServiceClient(cc *grpc.ClientConn) OfferServiceClient {
	return &offerServiceClient{cc}
}

func (c *offerServiceClient) GetOffer(ctx context.Context, in *GetOfferRequest, opts ...grpc.CallOption) (*Offer, error) {
	out := new(Offer)
	err := c.cc.Invoke(ctx, "/offer.OfferService/GetOffer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error) {
	out := new(ListOffersResponse)
	err := c.cc.Invoke(ctx, "/offer.OfferService/ListOffers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, "/offer.OfferService/ListCategories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) GetGoal(ctx context.Context, in *GetGoalRequest, opts ...grpc.CallOption) (*Goal, error) {
	out := new(Goal)
	err := c.cc.Invoke(ctx, "/offer.OfferService/GetGoal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) ListGoals(ctx context.Context, in *ListGoalsRequest, opts ...grpc.CallOption) (*ListGoalsResponse, error) {
	out := new(ListGoalsResponse)
	err := c.cc.Invoke(ctx, "/offer.OfferService/ListGoals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) ListOfferGeoCodes(ctx context.Context, in *ListOfferGeoCodesRequest, opts ...grpc.CallOption) (*ListOfferGeoCodesResponse, error) {
	out := new(ListOfferGeoCodesResponse)
	err := c.cc.Invoke(ctx, "/offer.OfferService/ListOfferGeoCodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offerServiceClient) GetTotalInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*TotalInfo, error) {
	out := new(TotalInfo)
	err := c.cc.Invoke(ctx, "/offer.OfferService/GetTotalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferServiceServer is the server API for OfferService service.
type OfferServiceServer interface {
	GetOffer(context.Context, *GetOfferRequest) (*Offer, error)
	ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error)
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetGoal(context.Context, *GetGoalRequest) (*Goal, error)
	ListGoals(context.Context, *ListGoalsRequest) (*ListGoalsResponse, error)
	ListOfferGeoCodes(context.Context, *ListOfferGeoCodesRequest) (*ListOfferGeoCodesResponse, error)
	GetTotalInfo(context.Context, *empty.Empty) (*TotalInfo, error)
}

func RegisterOfferServiceServer(s *grpc.Server, srv OfferServiceServer) {
	s.RegisterService(&_OfferService_serviceDesc, srv)
}

func _OfferService_GetOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).GetOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/GetOffer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).GetOffer(ctx, req.(*GetOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_ListOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).ListOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/ListOffers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).ListOffers(ctx, req.(*ListOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/ListCategories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_GetGoal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).GetGoal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/GetGoal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).GetGoal(ctx, req.(*GetGoalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_ListGoals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGoalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).ListGoals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/ListGoals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).ListGoals(ctx, req.(*ListGoalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_ListOfferGeoCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOfferGeoCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).ListOfferGeoCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/ListOfferGeoCodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).ListOfferGeoCodes(ctx, req.(*ListOfferGeoCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferService_GetTotalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferServiceServer).GetTotalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/offer.OfferService/GetTotalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferServiceServer).GetTotalInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _OfferService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "offer.OfferService",
	HandlerType: (*OfferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOffer",
			Handler:    _OfferService_GetOffer_Handler,
		},
		{
			MethodName: "ListOffers",
			Handler:    _OfferService_ListOffers_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _OfferService_ListCategories_Handler,
		},
		{
			MethodName: "GetGoal",
			Handler:    _OfferService_GetGoal_Handler,
		},
		{
			MethodName: "ListGoals",
			Handler:    _OfferService_ListGoals_Handler,
		},
		{
			MethodName: "ListOfferGeoCodes",
			Handler:    _OfferService_ListOfferGeoCodes_Handler,
		},
		{
			MethodName: "GetTotalInfo",
			Handler:    _OfferService_GetTotalInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "offer.proto",
}

func init() { proto.RegisterFile("offer.proto", fileDescriptor_offer_ea72e05c5e52454e) }

var fileDescriptor_offer_ea72e05c5e52454e = []byte{
	// 1438 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xb6, 0x24, 0xeb, 0x6f, 0x24, 0xcb, 0xca, 0x26, 0xb6, 0xd7, 0x72, 0x1c, 0xcb, 0x4c, 0x02,
	0xa8, 0x39, 0xd8, 0xa8, 0x0b, 0x34, 0x68, 0x73, 0xa9, 0xa2, 0x04, 0xae, 0xd0, 0xa4, 0x36, 0x68,
	0xa7, 0xc8, 0x8d, 0x58, 0x93, 0x2b, 0x79, 0x11, 0x8a, 0x64, 0xc9, 0x95, 0x0b, 0x3d, 0x44, 0x5f,
	0xa5, 0xef, 0xd4, 0x63, 0xdf, 0xa2, 0x98, 0xd9, 0xa5, 0xfe, 0x9c, 0xa0, 0x3d, 0xf4, 0xd0, 0x93,
	0x76, 0xbe, 0x99, 0x9d, 0x9d, 0xff, 0xa1, 0xa0, 0x11, 0x8f, 0x46, 0x32, 0x3d, 0x49, 0xd2, 0x58,
	0xc7, 0xac, 0x4c, 0x44, 0xe7, 0x60, 0x1c, 0xc7, 0xe3, 0x50, 0x9e, 0x12, 0x78, 0x33, 0x1d, 0x9d,
	0xca, 0x49, 0xa2, 0x67, 0x46, 0xa6, 0x73, 0xb4, 0xce, 0xd4, 0x6a, 0x22, 0x33, 0x2d, 0x26, 0x89,
	0x11, 0x70, 0xfe, 0xa8, 0x41, 0xf9, 0x02, 0xf5, 0xb0, 0x16, 0x14, 0x55, 0xc0, 0x0b, 0xdd, 0x42,
	0xaf, 0xec, 0x16, 0x55, 0xc0, 0xbe, 0x03, 0xf0, 0x53, 0x29, 0xb4, 0x0c, 0x3c, 0xa1, 0x79, 0xb1,
	0x5b, 0xe8, 0x35, 0xce, 0x3a, 0x27, 0x46, 0xdf, 0x49, 0xae, 0xef, 0xe4, 0x3a, 0xd7, 0xe7, 0xd6,
	0xad, 0x74, 0x5f, 0xe3, 0xd5, 0x69, 0x12, 0xe4, 0x57, 0x4b, 0xff, 0x7c, 0xd5, 0x4a, 0xf7, 0x35,
	0x63, 0xb0, 0x39, 0x9d, 0xaa, 0x80, 0x6f, 0x76, 0x0b, 0xbd, 0xba, 0x4b, 0x67, 0x76, 0x04, 0x0d,
	0x5f, 0x68, 0x39, 0x8e, 0xd3, 0x99, 0xa7, 0x02, 0x5e, 0x26, 0x13, 0x21, 0x87, 0x86, 0x24, 0x10,
	0x48, 0x5f, 0x65, 0x2a, 0x8e, 0x50, 0xa0, 0x62, 0x04, 0x72, 0x68, 0x18, 0xb0, 0xc7, 0x00, 0x22,
	0xf0, 0xa6, 0x99, 0x4c, 0x91, 0x5f, 0x25, 0x7e, 0x4d, 0x04, 0x1f, 0x32, 0x99, 0x0e, 0x03, 0xb6,
	0x07, 0x55, 0x11, 0x78, 0xb7, 0x22, 0xbb, 0xe5, 0x35, 0x7a, 0xb6, 0x22, 0x82, 0x1f, 0x45, 0x76,
	0xcb, 0x76, 0xa0, 0x82, 0xd7, 0xd2, 0x90, 0xd7, 0x09, 0x2f, 0x8b, 0xe0, 0x43, 0x1a, 0xb2, 0x7d,
	0xa8, 0x89, 0xc0, 0xd3, 0xf1, 0x27, 0x19, 0x71, 0x20, 0x46, 0x55, 0x04, 0xd7, 0x48, 0xb2, 0xe7,
	0xd0, 0x12, 0x81, 0xe7, 0xc7, 0x72, 0x34, 0x52, 0xbe, 0x92, 0x91, 0xe6, 0x8d, 0x6e, 0xa1, 0x57,
	0x70, 0xb7, 0x44, 0x30, 0x58, 0x80, 0xe8, 0x65, 0x24, 0x26, 0x92, 0x37, 0x8d, 0x97, 0x78, 0xc6,
	0xab, 0xf8, 0xeb, 0xf9, 0xf1, 0x24, 0x89, 0x33, 0xa5, 0x25, 0xdf, 0x22, 0xee, 0x16, 0xa2, 0x83,
	0x1c, 0x64, 0xbb, 0x50, 0xc9, 0xb4, 0xd0, 0xd3, 0x8c, 0xb7, 0xc8, 0x0d, 0x4b, 0x31, 0x0e, 0x55,
	0x9d, 0x8a, 0x28, 0x53, 0x9a, 0x6f, 0x77, 0x0b, 0xbd, 0x9a, 0x9b, 0x93, 0xec, 0x10, 0x40, 0x24,
	0xca, 0x53, 0xa3, 0x14, 0x9f, 0x6c, 0x13, 0xb3, 0x2e, 0x12, 0x35, 0x24, 0x80, 0x75, 0xa0, 0xe6,
	0x4f, 0xd3, 0x54, 0x46, 0xfe, 0x8c, 0x3f, 0xa0, 0x17, 0xe7, 0x34, 0xda, 0x19, 0xaa, 0xe8, 0x13,
	0x67, 0xc6, 0x4e, 0x3c, 0x23, 0x96, 0x4e, 0x43, 0xc9, 0x1f, 0x1a, 0x0c, 0xcf, 0xac, 0x8b, 0x09,
	0xc8, 0xfc, 0x54, 0x25, 0x5a, 0xc5, 0x11, 0x7f, 0x44, 0xac, 0x65, 0x08, 0xcd, 0x16, 0xc1, 0x9d,
	0xf2, 0x25, 0xdf, 0xc9, 0x43, 0x8c, 0x14, 0xb9, 0x13, 0x4f, 0x53, 0x5f, 0xf2, 0x5d, 0x83, 0x1b,
	0x8a, 0x3d, 0x82, 0x72, 0x92, 0xa2, 0xf8, 0x1e, 0xc5, 0xcf, 0x10, 0x18, 0x23, 0x3a, 0x78, 0x73,
	0x8b, 0xb9, 0x89, 0x11, 0xa1, 0x83, 0xdc, 0xec, 0x43, 0x00, 0x5f, 0x24, 0x9e, 0x8c, 0xc4, 0x4d,
	0x28, 0xf9, 0xbe, 0xf1, 0xd8, 0x17, 0xc9, 0x5b, 0x02, 0xd8, 0x01, 0x20, 0xe1, 0x05, 0x42, 0x85,
	0x33, 0xde, 0x31, 0xc5, 0xe0, 0x8b, 0xe4, 0x0d, 0xd2, 0x98, 0x5c, 0x64, 0xea, 0x59, 0x22, 0xf9,
	0x01, 0xf1, 0xaa, 0xbe, 0x48, 0xae, 0x67, 0x89, 0x64, 0x4f, 0x00, 0xee, 0x54, 0xa6, 0x6e, 0x54,
	0xa8, 0xf4, 0x8c, 0x3f, 0x36, 0x55, 0xb6, 0x40, 0x28, 0x32, 0x22, 0xfa, 0xc4, 0x0f, 0xc9, 0x64,
	0x3a, 0x63, 0x74, 0x45, 0x92, 0xa4, 0xf1, 0x9d, 0x0c, 0xf8, 0x13, 0xc2, 0xe7, 0x34, 0xfa, 0x68,
	0x6c, 0x38, 0x22, 0x0b, 0x0d, 0x81, 0xc6, 0xab, 0xc9, 0xd8, 0x13, 0x77, 0x42, 0x8b, 0x94, 0x77,
	0xc9, 0xbf, 0xba, 0x9a, 0x8c, 0xfb, 0x04, 0x60, 0xad, 0x23, 0x3b, 0x49, 0xe3, 0x60, 0xea, 0x6b,
	0x7e, 0x4c, 0x7c, 0xbc, 0x71, 0x69, 0x10, 0xf6, 0x14, 0xb6, 0x26, 0x42, 0xcb, 0x54, 0x89, 0xd0,
	0xa3, 0xe4, 0x39, 0x24, 0xd2, 0xcc, 0xc1, 0x77, 0x98, 0x44, 0x07, 0x9a, 0xe2, 0x4e, 0xa8, 0x50,
	0x58, 0x67, 0x9e, 0x92, 0x33, 0x2b, 0x18, 0xa5, 0x40, 0x85, 0x61, 0xc6, 0x9f, 0x11, 0xd3, 0x10,
	0xce, 0x31, 0x6c, 0x9f, 0x4b, 0x4d, 0x23, 0xc3, 0x95, 0xbf, 0x4e, 0x65, 0xa6, 0xd7, 0x27, 0x87,
	0x73, 0x09, 0xf0, 0xcb, 0x22, 0x2a, 0x47, 0xb0, 0x39, 0x89, 0x03, 0x49, 0xfc, 0xd6, 0x59, 0xe3,
	0xc4, 0x8c, 0xb0, 0xf7, 0x71, 0x20, 0x5d, 0x62, 0xb0, 0x63, 0x68, 0x8a, 0xd1, 0x48, 0x85, 0x4a,
	0x68, 0x89, 0xed, 0x59, 0x24, 0x45, 0x8d, 0x39, 0x36, 0x0c, 0x1c, 0x17, 0x9a, 0xfd, 0x65, 0xd3,
	0xfe, 0x0b, 0x9d, 0x7f, 0x15, 0xe1, 0xc1, 0x3b, 0x95, 0x19, 0x57, 0xb2, 0xdc, 0x97, 0x47, 0x50,
	0x0e, 0xd5, 0x44, 0x69, 0xeb, 0x8e, 0x21, 0xb0, 0x4a, 0xe3, 0xd1, 0x28, 0x93, 0xda, 0x2a, 0xb2,
	0x14, 0x6b, 0x43, 0x49, 0x05, 0x19, 0x2f, 0x75, 0x4b, 0xbd, 0xb2, 0x8b, 0x47, 0xf6, 0xf5, 0x4a,
	0x8d, 0x6c, 0xd2, 0xe8, 0x7b, 0x60, 0xed, 0x5b, 0x04, 0x65, 0xa5, 0x6c, 0x5e, 0xae, 0xe5, 0xa2,
	0x4c, 0x97, 0x1e, 0xda, 0x4b, 0xcb, 0x7e, 0xaf, 0x25, 0xe8, 0x2b, 0xa8, 0x99, 0xe6, 0x97, 0x19,
	0xaf, 0x74, 0x4b, 0xbd, 0xd6, 0xd9, 0x96, 0xbd, 0x74, 0x45, 0xb0, 0x3b, 0x67, 0x63, 0x55, 0xc7,
	0x69, 0x20, 0x53, 0xef, 0x66, 0x46, 0xe3, 0xaf, 0xee, 0x56, 0x89, 0x7e, 0x3d, 0x63, 0xa7, 0x00,
	0x86, 0x45, 0x25, 0x5f, 0xa3, 0x88, 0xb6, 0xad, 0x9e, 0x0b, 0x64, 0x60, 0xed, 0xbb, 0xf5, 0x38,
	0x3f, 0xa2, 0xae, 0xb1, 0x8c, 0x3d, 0x1f, 0x13, 0x60, 0xe6, 0x62, 0x75, 0x2c, 0xe3, 0x01, 0x86,
	0x1d, 0xbb, 0x59, 0x8a, 0xd4, 0xbf, 0xb5, 0x73, 0xd1, 0x52, 0xce, 0x25, 0xb0, 0xe5, 0x50, 0x67,
	0x49, 0x1c, 0x65, 0x92, 0x3d, 0xa3, 0xa8, 0xca, 0x34, 0xe3, 0x85, 0x6e, 0xa9, 0xd7, 0x38, 0x6b,
	0xe6, 0xaf, 0x52, 0x71, 0x59, 0x1e, 0x66, 0x44, 0xc7, 0x5a, 0x84, 0x36, 0xf4, 0x86, 0x70, 0x4e,
	0xa0, 0x36, 0xb0, 0x0b, 0xe0, 0xde, 0xe6, 0xca, 0xa7, 0x6b, 0x71, 0x31, 0x5d, 0x9d, 0x3d, 0xd8,
	0x41, 0x0b, 0xec, 0x1d, 0x25, 0xf3, 0x84, 0x3b, 0x43, 0xd8, 0x5d, 0x67, 0x58, 0xf3, 0x4e, 0x21,
	0xdf, 0x31, 0x4a, 0xe6, 0x26, 0x6e, 0x5b, 0x13, 0xf3, 0xb7, 0xdd, 0x25, 0x11, 0xe7, 0xf7, 0x22,
	0x6c, 0x9e, 0xc7, 0x22, 0xfc, 0x9f, 0xac, 0x52, 0xcc, 0x39, 0x1a, 0xeb, 0xd9, 0x75, 0x5a, 0x76,
	0xab, 0x44, 0x0f, 0x29, 0x42, 0x94, 0x6d, 0xb3, 0x4a, 0xe9, 0x8c, 0x33, 0x7c, 0x79, 0x6f, 0x55,
	0x68, 0x58, 0x2d, 0x43, 0xb8, 0x0e, 0x13, 0x31, 0xf3, 0x54, 0x44, 0x25, 0x84, 0x43, 0x59, 0xcc,
	0x86, 0x11, 0xae, 0x4f, 0x84, 0xe3, 0xa9, 0xa6, 0xea, 0x29, 0xb8, 0x28, 0x75, 0x31, 0xd5, 0xce,
	0x2b, 0x68, 0x9d, 0x4b, 0x8d, 0x11, 0xf9, 0xc2, 0xa4, 0x58, 0x31, 0xb1, 0xb8, 0x62, 0xa2, 0xd3,
	0x87, 0x36, 0xe6, 0x05, 0x6f, 0xcf, 0x9b, 0xd3, 0xb6, 0x5b, 0x61, 0xd1, 0x6e, 0x07, 0x50, 0xcf,
	0x15, 0x64, 0xbc, 0x48, 0x78, 0xcd, 0x6a, 0xc8, 0x9c, 0x6f, 0x4d, 0x83, 0x5b, 0x15, 0x36, 0xab,
	0xc7, 0x50, 0x1e, 0x23, 0x60, 0x13, 0x9a, 0xcf, 0x0e, 0xb2, 0xd2, 0x70, 0x9c, 0xf7, 0xd0, 0xa4,
	0x12, 0x3c, 0xb7, 0x55, 0xfd, 0xef, 0xad, 0xc6, 0xc0, 0x52, 0x5f, 0x94, 0x4c, 0xe9, 0xe1, 0xd9,
	0x79, 0x09, 0x7c, 0x5e, 0xfc, 0x56, 0xe5, 0xdc, 0xa3, 0x15, 0xfb, 0x0b, 0x6b, 0xf6, 0x7f, 0x84,
	0xfd, 0xcf, 0x5c, 0xb4, 0x7e, 0xbc, 0x82, 0x6d, 0x73, 0x33, 0xef, 0xc5, 0xdc, 0xa3, 0x87, 0xcb,
	0x5d, 0x64, 0xaf, 0xb9, 0x5b, 0xf1, 0xb2, 0x12, 0x27, 0x81, 0xfa, 0x35, 0xb6, 0xd1, 0x30, 0x1a,
	0xc5, 0xf4, 0x79, 0x15, 0x4f, 0x23, 0xed, 0x91, 0x8c, 0xf5, 0x13, 0x08, 0x32, 0x5f, 0x86, 0xcf,
	0xa1, 0x65, 0x04, 0xf2, 0x4f, 0x2e, 0xeb, 0xf5, 0x16, 0xa1, 0xf3, 0x36, 0xc4, 0xb5, 0x4a, 0x62,
	0x63, 0x19, 0x53, 0x00, 0x70, 0xad, 0x22, 0x70, 0x2e, 0xe3, 0x17, 0x07, 0xb0, 0x89, 0xe3, 0x99,
	0x01, 0x54, 0x5e, 0xcf, 0xf0, 0xbb, 0xab, 0xbd, 0xc1, 0xaa, 0x50, 0xea, 0x87, 0x61, 0xbb, 0xf0,
	0xe2, 0x27, 0xa8, 0x98, 0x89, 0xc5, 0x9a, 0x50, 0xa3, 0x37, 0x7f, 0x96, 0xbf, 0xb5, 0x37, 0xd8,
	0x36, 0x34, 0x88, 0xea, 0xfb, 0x5a, 0xdd, 0xc9, 0x76, 0x81, 0xb5, 0x00, 0x08, 0xb8, 0x14, 0xd3,
	0x4c, 0xb6, 0x8b, 0x8c, 0x41, 0x8b, 0xe8, 0x61, 0xd4, 0x4f, 0xfd, 0x5b, 0x94, 0x29, 0xbd, 0x78,
	0x02, 0xf5, 0xf9, 0xd8, 0xa2, 0x27, 0xae, 0x06, 0xed, 0x0d, 0x56, 0x83, 0xcd, 0x37, 0x6f, 0xaf,
	0x06, 0xed, 0xc2, 0xd9, 0x9f, 0x25, 0x9b, 0xde, 0x2b, 0x99, 0xd2, 0x27, 0xc8, 0x19, 0xd4, 0xf2,
	0x8d, 0xc6, 0x76, 0xf3, 0x72, 0x58, 0x5d, 0x71, 0x9d, 0x95, 0xd1, 0xe4, 0x6c, 0xb0, 0x01, 0xc0,
	0x62, 0xa0, 0x31, 0x6e, 0xb9, 0xf7, 0xd6, 0x49, 0x67, 0xff, 0x33, 0x1c, 0x93, 0x40, 0x67, 0x83,
	0x5d, 0x40, 0x6b, 0x75, 0xf4, 0xb0, 0xc7, 0x4b, 0xe2, 0xf7, 0x46, 0x55, 0xe7, 0xf0, 0x0b, 0xdc,
	0xb9, 0xc2, 0x53, 0xa8, 0xda, 0x86, 0x63, 0x3b, 0x0b, 0x47, 0x96, 0x1a, 0xb0, 0xb3, 0x5c, 0xee,
	0xce, 0x06, 0xfb, 0x01, 0xea, 0xf3, 0x0e, 0x61, 0x7b, 0x4b, 0xea, 0x97, 0xdb, 0xae, 0xc3, 0xef,
	0x33, 0xe6, 0x4f, 0x7e, 0x5c, 0x5a, 0xa2, 0x79, 0x79, 0xb1, 0xa3, 0x75, 0xaf, 0xd7, 0xca, 0xbe,
	0xd3, 0xfd, 0xb2, 0xc0, 0x5c, 0xf3, 0xf7, 0xd0, 0x3c, 0x97, 0x7a, 0x51, 0xa6, 0xbb, 0xf7, 0xa6,
	0xde, 0x5b, 0xfc, 0xa3, 0xd3, 0xc9, 0x77, 0xd5, 0x5c, 0xd2, 0xd9, 0xb8, 0xa9, 0x90, 0xcc, 0x37,
	0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xce, 0x8a, 0x16, 0xbd, 0x30, 0x0d, 0x00, 0x00,
}
